services:  
  backend:
    build:
        context: .
        dockerfile: Api/Source/Adapter/Adapter.RestApi/Dockerfile
    image: ${DOCKER_REGISTRY-}futionsapirestful   
    container_name: Futions-Api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__Sql: ${SQL_CONNECTION_STRING}
      CacheConfig__HostAndPort: ${CACHE_CONFIG_HOST_AND_PORT}
      CacheConfig__AccessKey: ${CACHE_CONFIG_ACCESS_KEY}
      CacheConfig__Ssl: ${CACHE_CONFIG_SSL}
      CacheConfig__Timeout: ${CACHE_CONFIG_TIMEOUT}
      Authentication__Audience: ${AUTH_AUDIENCE}
      Authentication__MetadataAddress: ${AUTH_METADATA_ADDRESS}
      Authentication__RequireHttpsMetadata: ${AUTH_REQUIRE_HTTPS_METADATA}
      Authentication__TokenValidationParameters__ValidateLifetime: "true"
      Authentication__TokenValidationParameters__ValidateAudience: "true"
      Authentication__TokenValidationParameters__ValidateIssuer: "true"
      Authentication__TokenValidationParameters__ClockSkew: "00:00:00"
      Authentication__TokenValidationParameters__ValidIssuers__0: ${AUTH_VALID_ISSUER_0}
      Authentication__TokenValidationParameters__ValidIssuers__1: ${AUTH_VALID_ISSUER_1}
    depends_on:
      - redis
    ports:
      - "${API_PORT}:8080"
    restart: unless-stopped
    networks:
      - futions-network                     

  scheduler:
    build:
      context: .
      dockerfile: Api/Source/Adapter/Adapter.Scheduler/Dockerfile
    image: ${DOCKER_REGISTRY-}futionsscheduler
    container_name: Futions-Scheduler
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      ConnectionStrings__Sql: ${SQL_CONNECTION_STRING}
      Outbox__IntervalInSeconds: ${OUTBOX_INTERVAL_IN_SECONDS}
      Outbox__BatchSize: ${OUTBOX_BATCH_SIZE}
    restart: unless-stopped
    networks:
      - futions-network

  redis:
    image: redis:latest
    container_name: Futions-Redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - futions-network
    volumes:
      - redis-data:/data

  serilog:
    image: datalust/seq:latest
    container_name: Futions-Serilog
    environment:
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 9090:80    
    networks:
      - futions-network

networks:
  futions-network:
    driver: bridge

volumes:
  redis-data: