services:  
  crm.backend:  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Sql: Server=sqlserver,1433;Database=Futions;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;
      ConnectionStrings__Redis: Development redis info
    depends_on:
      - sqlserver  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  crm.scheduler: 
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__Sql: Server=sqlserver,1433;Database=Futions;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;
      Outbox__IntervalInSeconds: 5
      Outbox__BatchSize: 50
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Futions-SqlServer
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - futions-network 

volumes:
  sqlserver-data:   