services:  
  crm.backend:
    build:
        context: .
        dockerfile: Api/Source/Adapter/Adapter.RestApi/Dockerfile
    image: ${DOCKER_REGISTRY-}futionscrmapirestful   
    container_name: Futions-Api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__Sql: ${SQL_CONNECTION_STRING}
      CacheConfig__HostAndPort: ${CACHE_CONFIG_HOST_AND_PORT}
      CacheConfig__AccessKey: ${CACHE_CONFIG_ACCESS_KEY}
      CacheConfig__Ssl: ${CACHE_CONFIG_SSL}
      CacheConfig__Timeout: ${CACHE_CONFIG_TIMEOUT}
    depends_on:
      - redis
    ports:
      - "${API_PORT}:8080"
    restart: unless-stopped
    networks:
      - futions-network                     

  crm.scheduler:
    build:
      context: .
      dockerfile: Api/Source/Adapter/Adapter.Scheduler/Dockerfile
    image: ${DOCKER_REGISTRY-}futionscrmscheduler
    container_name: Futions-Scheduler
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      ConnectionStrings__Sql: ${SQL_CONNECTION_STRING}
      Outbox__IntervalInSeconds: ${OUTBOX_INTERVAL_IN_SECONDS}
      Outbox__BatchSize: ${OUTBOX_BATCH_SIZE}
    restart: unless-stopped
    networks:
      - futions-network

  redis:
    image: redis:7-alpine
    container_name: Futions-Redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - futions-network
    volumes:
      - redis-data:/data

networks:
  futions-network:
    driver: bridge

volumes:
  redis-data: