services:  
  backend:  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Sql: Server=sqlserver,1433;Database=Futions;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;
      CacheConfig__HostAndPort: redis:6379
      CacheConfig__AccessKey: ""
      CacheConfig__Ssl: "false"
      CacheConfig__Timeout: "5000"
      Authentication__Audience: account
      Authentication__MetadataAddress: http://host.docker.internal:18080/realms/Futions/.well-known/openid-configuration
      Authentication__RequireHttpsMetadata: "false"
      Authentication__TokenValidationParameters__ValidIssuers__0: http://localhost:18080/realms/Futions
      Authentication__TokenValidationParameters__ValidIssuers__1: http://host.docker.internal:18080/realms/Futions
    depends_on:
      - sqlserver  
      - redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  scheduler: 
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__Sql: Server=sqlserver,1433;Database=Futions;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;
      Outbox__IntervalInSeconds: 5
      Outbox__BatchSize: 50
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Futions-SqlServer
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - futions-network 

volumes:
  sqlserver-data:  